src/main/java/com/jaoafa/mymaid4/event/Event_AntiProblemTeleport.java
拝啓　春寒ようやくゆるむ候、いかがお過ごしでしょうか
　さて、今回ご紹介する商品はこちらッ！「Event_AntiProblemTeleport」でございます！
この商品はアホみたいに遠い場所にテレポートして鯖を落とす輩が絶えないことから開発されました。
これさえあればもう二度とサーバーが落ちた挙げ句プレイヤーデータを直接書き換えるなんて面倒なことをしなくてすみます。さぁ今すぐプルリクを承認しろ
=> feat: 極端に遠い地点へのテレポートを阻止する

src/main/java/com/jaoafa/mymaid4/event/Event_SSKColor.java, src/main/java/com/jaoafa/mymaid4/lib/SKKColorManager.java
LimitedVerifiedをGrayにする機能を除き実装しました
=> feat: SSKColorsを実装

src/main/java/com/jaoafa/mymaid4/event/Event_SKKColor.java, src/main/java/com/jaoafa/mymaid4/lib/SKKColorManager.java
ブランチ操作が下手なのは許してください...
SKKColorを直しました
=> fix: SKKColor (#72)

CONTRIBUTING.md, README.md
=> chore: READMEとCONTRIBUTINGの変更

pom.xml, src/main/java/com/jaoafa/mymaid4/Main.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_LoginText.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_SKKColor.java, src/main/java/com/jaoafa/mymaid4/event/Event_CustomJoinMessage.java, src/main/java/com/jaoafa/mymaid4/event/Event_SKKColor.java, src/main/java/com/jaoafa/mymaid4/event/Event_Vote.java, src/main/java/com/jaoafa/mymaid4/httpServer/HTTP_VoteFill.java, src/main/java/com/jaoafa/mymaid4/httpServer/MyMaidServer.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java, src/main/java/com/jaoafa/mymaid4/lib/PlayerVoteDataMCJP.java, src/main/java/com/jaoafa/mymaid4/lib/PlayerVoteDataMono.java, src/main/java/com/jaoafa/mymaid4/lib/SKKColorManager.java
投票関連について追加しました。が、自分の書いたコードを信用できないのでレビューお願いします。
ざっと見て不審なところがないかどうかだけ確かめてもらえれば構いません
=> feat: 投票関連追加

src/main/java/com/jaoafa/mymaid4/lib/ChatBan.java, src/main/java/com/jaoafa/mymaid4/lib/EBan.java, src/main/java/com/jaoafa/mymaid4/lib/Jail.java
=> fix: Jail, EBan, ChatBanなどが機能しない問題の修正？

src/main/java/com/jaoafa/mymaid4/event/Event_CustomJoinMessage.java, src/main/java/com/jaoafa/mymaid4/event/Event_SKKColor.java, src/main/java/com/jaoafa/mymaid4/lib/SKKColorManager.java
=> fix: Event_CustomJoinMessage で IllegalStateException を抑制 #171

src/main/java/com/jaoafa/mymaid4/command/Cmd_Elytra.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_Hat.java, src/main/java/com/jaoafa/mymaid4/lib/EBan.java
+ elytraの不要なnullチェック削除, EBanのデバッグ消し忘れ
=> feat: #173 hatコマンドの実装

src/main/java/com/jaoafa/mymaid4/command/Cmd_Looking.java, src/main/java/com/jaoafa/mymaid4/event/Event_Looking.java, src/main/java/com/jaoafa/mymaid4/event/Event_MCBansLoginCheck.java, src/main/java/com/jaoafa/mymaid4/event/Event_PlayerCheckPreLogin.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java
=> feat: lookingコマンドの実装

src/main/java/com/jaoafa/mymaid4/event/Event_ManageCPPerms.java
=> feat: CoreProtectのコマンドパーミッションノード制御

src/main/java/com/jaoafa/mymaid4/command/Cmd_Looking.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_Rider.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
=> feat: #218 riderの実装

.idea/misc.xml, src/main/java/com/jaoafa/mymaid4/discordEvent/DiscordEvent_ListCmd.java
=> feat: #83 No.61の実績を追加

src/main/java/com/jaoafa/mymaid4/event/Event_KillAfterRespawn.java
=> feat: #246 死亡してから3分後にリスポーンするように

src/main/java/com/jaoafa/mymaid4/event/Event_FirstLogin.java
またブランチ間違えた！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
=> fix: ユーザーページへのリンクをuser.jaoafaに変更

src/main/java/com/jaoafa/mymaid4/event/Event_DisableKicks.java, src/main/java/com/jaoafa/mymaid4/event/Event_FirstLogin.java, src/main/java/com/jaoafa/mymaid4/event/Event_NotifyKick.java, src/main/java/com/jaoafa/mymaid4/event/Event_PacketLimiterKick.java
=> feat: #254 パケ蹴りされたときに通知するように + キック関連の処理一通り追加

src/main/java/com/jaoafa/mymaid4/event/Event_ProtectionOldWorlds.java
=> feat: #251 旧ワールドの保護機能追加

src/main/java/com/jaoafa/mymaid4/command/Cmd_FlySpeed.java, src/main/java/com/jaoafa/mymaid4/event/Event_FlySpeed.java, src/main/java/com/jaoafa/mymaid4/event/Event_OnlineTimeDB.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java
=> feat: #260

src/main/java/com/jaoafa/mymaid4/command/Cmd_History.java, src/main/java/com/jaoafa/mymaid4/event/Event_History.java, src/main/java/com/jaoafa/mymaid4/lib/Historyjao.java
=> feat: #267 鯖内およびDiscordでの通知設定ができるように

src/main/java/com/jaoafa/mymaid4/command/Cmd_DT.java
=> feat: dt neartp

src/main/java/com/jaoafa/mymaid4/command/Cmd_Test.java, src/main/java/com/jaoafa/mymaid4/event/Event_Antijaoium.java, src/main/java/com/jaoafa/mymaid4/lib/NMSManager.java
=> feat: jaoiumロギング

src/main/java/com/jaoafa/mymaid4/event/Event_Set43.java
=> feat: #287 set 43を従来動作へ戻す

src/main/java/com/jaoafa/mymaid4/command/Cmd_MakeCmd.java
=> feat: #294 makecmdコマンド作成

pom.xml, src/main/java/com/jaoafa/mymaid4/Main.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
=> feat: mymaidhelpコマンドの追加、各コマンドのヘルプ引数追加、エラーメッセージの日本語化など

pom.xml, src/main/java/com/jaoafa/mymaid4/command/Cmd_DedMessage.java, src/main/java/com/jaoafa/mymaid4/event/Event_DedMessage.java, src/main/java/com/jaoafa/mymaid4/lib/DedMessage.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
=> feat: #234 dedmessageの追加

src/main/java/com/jaoafa/mymaid4/Main.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_MyMaid4.java, src/main/java/com/jaoafa/mymaid4/event/Event_BlackList.java, src/main/java/com/jaoafa/mymaid4/lib/Blacklist.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java
=> feat: #185 ブラックリストの代替製作完了

src/main/java/com/jaoafa/mymaid4/Main.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_Bug.java, src/main/java/com/jaoafa/mymaid4/event/Event_Bug.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidConfig.java
=> feat: bugコマンドの追加

src/main/java/com/jaoafa/mymaid4/event/Event_Looking.java
lookingしている際、IllegalArgumentException: pitch not finiteが発生しうる問題の修正。tp直後に発生
- close #309
=> fix: IllegalArgumentException: pitch not finite

src/main/java/com/jaoafa/mymaid4/event/Event_Looking.java
=> fix: #309 isInfiniteだった

src/main/java/com/jaoafa/mymaid4/Main.java, src/main/java/com/jaoafa/mymaid4/event/Event_AntiTeleportToNewPlayers.java, src/main/java/com/jaoafa/mymaid4/event/Event_AntiTeleportToSpectator.java, src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java
ツールバーの利用制限機能。対象は Default と Verified
- close #325 
=> feat: ツールバーの利用制限機能追加

src/main/java/com/jaoafa/mymaid4/command/Cmd_Help.java
=> feat: #324 helpコマンドの実装

src/main/java/com/jaoafa/mymaid4/event/Event_Antijaoium.java
Wurstによって作成されるアイテムが増えたらしいので、追加。
=> fix: 悪意のあるアイテムを追加

CONTRIBUTING.md
以下を追加
- ローカル変数はなにかしらの理由がある場合を除き小文字で始めてください。
- 発生しているエラーなどはコミット・プルリクエスト前にすべて修正してください。
=> chore: CONTRIBUTINGの変更

pom.xml, src/main/java/com/jaoafa/mymaid4/command/Cmd_Bug.java
=> fix: #354 okhttpのバージョンダウン

src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java
=> fix: 耐久値のみのNBTの場合に許容するように(耐久値が減ってもそれ以外のNBTデータがある場合は不可)

src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java
=> fix: インベントリに同じアイテムがある場合にtoolbarとして判定しないように

src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java
=> fix: toolbar関連のnullpointerexception

src/main/java/com/jaoafa/mymaid4/event/Event_LongTimeNoSee.java
=> feat: longtimenosee

src/main/java/com/jaoafa/mymaid4/event/Event_PlayerCountNotify.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
=> feat: #261 入退出時にプレイヤー数を表示するように

src/main/java/com/jaoafa/mymaid4/event/Event_Antijaoium.java
=> fix: #393 Wurstなど検知時のメッセージ修正

src/main/java/com/jaoafa/mymaid4/lib/CarrierPigeon.java
=> fix: #394 tempmute時、pigeonで発せられたメッセージの無効化

src/main/java/com/jaoafa/mymaid4/lib/Blacklist.java
=> fix: #379 blacklistの過度通知改善

src/main/java/com/jaoafa/mymaid4/event/Event_NotFadeIce.java
=> feat: #375 氷を解けなくした

src/main/java/com/jaoafa/mymaid4/event/Event_NotifyTPDiscord.java
=> feat: #371 tpコマンドによるテレポート時にDiscord#server-chatでもそれを表示するように

src/main/java/com/jaoafa/mymaid4/command/Cmd_Wt.java
=> fix: #268 コマンドブロックからwtコマンドが実行された際にうまく動作しない不具合

src/main/java/com/jaoafa/mymaid4/event/Event_AntiTNTCart.java
=> feat: #364 TNTカートを設置できないように

src/main/java/com/jaoafa/mymaid4/event/Event_AntiEndPortal.java, src/main/java/com/jaoafa/mymaid4/event/Event_AntiWither.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
=> feat: #414 エンドポータルの設置禁止

src/main/java/com/jaoafa/mymaid4/command/Cmd_wire.java
sel polyでの3地点以上の同時設置に対応
glowing時間の調整
=> feat: sel polyを用いた3地点以上の同時選択への対応、glowing効果時間の修正

src/main/java/com/jaoafa/mymaid4/command/Cmd_Bug.java, src/main/java/com/jaoafa/mymaid4/event/Event_Bug.java, src/main/java/com/jaoafa/mymaid4/lib/NMSManager.java
=> fix: #413 bugの本かどうかをNBTタグで判定するように

src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java
=> fix: #429 Headで出した頭をホットバーに置くとAntiToolBarに引っかかる

src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java
del,delweの効果範囲を半径1m→2mへ変更、ワイヤーの最大距離間を64m→128mに緩和。
数値の変更のみなので動作確認はしていません
=> del,delweの効果範囲を半径1m→2mへ変更、ワイヤーの最大距離間を64m→128mに緩和。

.github/workflows/deploy.yml
=> feat: deploy action #434

.github/workflows/deploy.yml
=> fix: deploy change message

src/main/java/com/jaoafa/mymaid4/command/Cmd_History.java, src/main/java/com/jaoafa/mymaid4/event/Event_AntiProblemCommand.java, src/main/java/com/jaoafa/mymaid4/event/Event_Antijaoium.java, src/main/java/com/jaoafa/mymaid4/event/Event_History.java, src/main/java/com/jaoafa/mymaid4/lib/Historyjao.java
jaoiumのシステム調整を含む。
ソースコード見るたび汚くて書き直したくなるjaoiumのコードだけど、よりよいコードが思いつかないんだよなあ…
=> feat: #431 RegularでのjaoHistoryへのデータ追加可能化・データ追加の自動化

src/main/java/com/jaoafa/mymaid4/event/Event_History.java, src/main/java/com/jaoafa/mymaid4/lib/Historyjao.java
=> feat: 同日中の2回目以降通知を除外

src/main/java/com/jaoafa/mymaid4/event/Event_AntiEndPortal.java, src/main/java/com/jaoafa/mymaid4/event/Event_AntiNetherPortal.java, src/main/java/com/jaoafa/mymaid4/lib/Blacklist.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
=> feat: #373 ネザーポータルの生成制限

src/main/java/com/jaoafa/mymaid4/command/Cmd_Wire.java, src/main/java/com/jaoafa/mymaid4/event/Event_AntiDisableInvisibilityWire.java, src/main/java/com/jaoafa/mymaid4/event/Event_AntiKillWire.java, src/main/java/com/jaoafa/mymaid4/event/Event_InvisibilityWireContinuation.java
・コウモリの透明化エフェクトが消えても再度透明化エフェクトが自動で付くように。
・ワイヤーの出現位置を調整し、ワイヤーの端がブロックの中心に来るように。
・コウモリに付くタグをwireUnitからCmdWire1,CmdWire2へ変更。
・撤去したリードの本数をカウントしてたけど色々いじってたら上手くカウントされなくなって面倒なので消去しました。
・その他文章の修正など
=> wireコマンド修正。コウモリの透明化エフェクト永続化やワイヤーの出現位置の調整など

src/main/java/com/jaoafa/mymaid4/event/Event_SpectatorDynmapHide.java
=> feat: #452 スペクテイター時にDynmapから姿を消す

src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
=> fix: #448 メッセージに含まれるURLのスキームを必須化

.github/workflows/build.yml, .run/buildAndTest.bat, CONTRIBUTING.md, pom.xml
=> chore: upgraded/supported to java 11

src/main/java/com/jaoafa/mymaid4/command/Cmd_Var.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_VarCmd.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_Weather.java, src/main/java/com/jaoafa/mymaid4/event/Event_SKKColor.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java, src/main/java/com/jaoafa/mymaid4/lib/VariableManager.java
=> feat: #360 var,varcmdコマンドの実装

.github/workflows/PaperServerTest.yml
起動後、1分以内にExceptionが出たら OR 1分後にEnableじゃなかったらエラーという条件
https://github.com/jaoafa/CheckPluginEnabling
=> feat: GitHub ActionsでPaperサーバの1分テストを導入

src/main/java/com/jaoafa/mymaid4/command/Cmd_DT.java
=> feat: ほかのエンティティ・プレイヤーをテレポートできるように

src/main/java/com/jaoafa/mymaid4/command/Cmd_Hide.java
=> fix: #503 hide <target>の引数説明追加

pom.xml, src/main/java/com/jaoafa/mymaid4/event/Event_AdvancementDiscordNotify.java, src/main/java/com/jaoafa/mymaid4/event/Event_FirstLogin.java, src/main/java/com/jaoafa/mymaid4/event/Event_PacketLimiterKick.java, src/main/java/com/jaoafa/mymaid4/event/Event_TempMute.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
- `cloud-paper`: 1.4.0 -> 1.5.0
- `cloud-minecraft-extras`: 1.4.0 -> 1.5.0
- `JDA`: 4.3.0_280 -> 4.3.0_295
- `worldguard-bukkit`: 7.0.4 -> 7.0.5
=> chore(deps): 依存パッケージアップデート

pom.xml, src/main/java/com/jaoafa/mymaid4/event/Event_SpectatorDynmapHide.java
close #528 
fix: ビルド時のMETA-INF系エラーの修正(ついで)
=> fix: スペクテイターモード切替できないユーザーが切り替えようとしたときにDynmapから姿が消える問題の修正

src/main/java/com/jaoafa/mymaid4/command/Cmd_Head.java
=> fix: #525 headコマンドで対象プレイヤー名を指定したときにプレイヤー名の表示がおかしい不具合の修正

src/main/java/com/jaoafa/mymaid4/event/Event_CommandSender.java
=> delete: debug

src/main/java/com/jaoafa/mymaid4/command/Cmd_Wt.java
=> fix: #457 wt時、ワールド名が正常に表示されない不具合を修正

src/main/java/com/jaoafa/mymaid4/command/Cmd_DedMessage.java
dedmessageのlistの改ページdtのままでしたよ
一応「dedmessage list <任意id>」を直で打って正常に動作するのは確認したけどこのやり方がダメだったら突き返して
=> dedmessageのlistの改ページdtのままでしたよ

src/main/java/com/jaoafa/mymaid4/command/Cmd_DedMessage.java, src/main/java/com/jaoafa/mymaid4/lib/DedMessage.java
=> Fix: DedMessageで初回実行時に何も出てこない問題を修正

src/main/java/com/jaoafa/mymaid4/event/Event_PacketLimiterKick.java
5回以上パケットキックされた場合自動的にEBanする（ただし鯖再起でカウントはリセット）
- close #555
=> feat: #555 5回以上パケ蹴りされた場合自動的にEBan

src/main/java/com/jaoafa/mymaid4/command/Cmd_InvEdit.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_InvShow.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_Invshow.java
invshow, inveditコマンドの実装
- close #358
=> invshow, inveditコマンドの実装

src/main/java/com/jaoafa/mymaid4/command/Cmd_DiscordLink.java
https://github.com/jaoafa/jaoweb-docs/issues/88
=> feat: 3か月経過による自動切断後、1週間以内に再接続した場合に元の権限を自動付与する

src/main/java/com/jaoafa/mymaid4/command/Cmd_Body.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_Boots.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_Legs.java
=> feat: #369 body, legs, bootsコマンドの追加

src/main/java/com/jaoafa/mymaid4/command/Cmd_TpAlias.java, src/main/java/com/jaoafa/mymaid4/event/Event_Antijaoium.java, src/main/java/com/jaoafa/mymaid4/event/Event_TpAlias.java, src/main/java/com/jaoafa/mymaid4/lib/TeleportAlias.java
=> feat: #366 tpaliasの追加

src/main/java/com/jaoafa/mymaid4/event/Event_AntiBigSlime.java
=> feat: #196 極端に大きいスライム・マグマキューブを召喚できないように

src/main/java/com/jaoafa/mymaid4/command/Cmd_jaoBox.java, src/main/java/com/jaoafa/mymaid4/event/Event_jaoBox.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java
=> jaoBoxの更新ができるユーザをAMRに制限・登録情報変更ログ

src/main/java/com/jaoafa/mymaid4/event/Event_ViaVerCheck.java
=> fix: #685 JSON形式とコードに差異があったので修正

src/main/java/com/jaoafa/mymaid4/event/Event_NewPlayerAutoBlMap.java
=> feat: 初ログインユーザーのブロック編集マップにて、中央市近辺だけ切りぬくように変更

src/main/java/com/jaoafa/mymaid4/command/Cmd_DiscordLink.java
=> fix: jaoafa/Javajaotan2#222 元の権限への自動復元処理を修正

src/main/java/com/jaoafa/mymaid4/command/Cmd_DiscordLink.java
=> fix: jaoafa/Javajaotan2#219 CommunityRegularの権限復元に対応、同時にDiscordロールも復元する

pom.xml
providedじゃないとjsa2のMain.getJavaPlugin()がnullになる…
=> fix: jSA2が正常に動作しなくなる不具合修正

src/main/java/com/jaoafa/mymaid4/lib/SKKColorManager.java, src/test/java/com/jaoafa/mymaid4/SKKColorTest.java
=> fix: #754 四角色の計算式修正（+テストケース追加）

src/main/java/com/jaoafa/mymaid4/command/Cmd_DT.java
=> fix: #756 dt tpコマンドにて、第4引数のMarkerNameのところでMarkerTypeのサジェストが出てくる問題を修正

src/main/java/com/jaoafa/mymaid4/command/Cmd_Light.java
=> feat: lightコマンド追加

src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java
以前 #735 で「楽園の場所を変更」と書きましたが、全くしていなかったので、修正しました。
=> fix: paradise location

.github/workflows/PaperServerTest.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/dependencies-update.yml, .github/workflows/qodana-quality.yml, .github/workflows/release.yml, pom.xml
close #769
- #728
- #747
- #748
- #749
- #750
- #752
- #753
- #761
- #762
=> 依存パッケージアップデート 2022/03/28

src/main/java/com/jaoafa/mymaid4/event/Event_AdvancementDiscordNotify.java, src/main/java/com/jaoafa/mymaid4/event/Event_GameModeCmd.java
=> fix: #785 機能の説明文修正

src/main/java/com/jaoafa/mymaid4/event/Event_AntiPotion.java
=> feat: ポーションの利用制限

src/main/java/com/jaoafa/mymaid4/event/Event_Vote.java
=> feat: ログイン時、未投票の場合に通知する

pom.xml, src/main/java/com/jaoafa/mymaid4/event/Event_EBan.java, src/main/java/com/jaoafa/mymaid4/event/Event_Jail.java, src/main/java/com/jaoafa/mymaid4/lib/Jail.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
=> feat: Jail/EBanに各種インタラクト制限追加、jSA2をインクルード

pom.xml
=> fix: jSA2 v2.5.23

.idea/misc.xml, src/main/java/com/jaoafa/mymaid4/event/Event_WhereAreYou.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
=> feat: 「みんなどこ」と発言した場合にjaotanが自動返信する

src/main/java/com/jaoafa/mymaid4/event/Event_PlayerCheckPreLogin.java
=> fix: ログイン時の国情報が取れなかった場合の処理修正

src/main/java/com/jaoafa/mymaid4/event/Event_PlayerCheckPreLogin.java
=> fix: 許可していない国からのログインができてしまう不具合の修正

.idea/misc.xml, src/main/java/com/jaoafa/mymaid4/event/Event_ChatBan.java, src/main/java/com/jaoafa/mymaid4/lib/ChatBan.java
=> feat: ChatBanされている場合はw(1v1 tell)とか使えないように

src/main/java/com/jaoafa/mymaid4/command/Cmd_Body.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_Boots.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_Legs.java
=> fix: #846 body, legs, bootsが正常に動作しない不具合修正

src/main/java/com/jaoafa/mymaid4/command/Cmd_Spawn.java
=> feat: spawnコマンドのエイリアスにhubとlobbyを追加

src/main/java/com/jaoafa/mymaid4/command/Cmd_Elytra.java
=> feat: elytraコマンド実行時、いずれか装備している場合はそれを装備しないように

src/main/java/com/jaoafa/mymaid4/command/Cmd_ItemFrame.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_Lead.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
=> feat: itemfameコマンドの追加

src/main/java/com/jaoafa/mymaid4/command/Cmd_ItemEdit.java
=> feat: itemeditコマンドの追加

src/main/java/com/jaoafa/mymaid4/command/Cmd_Wtp.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java
=> feat: wtpコマンドの追加

src/main/java/com/jaoafa/mymaid4/command/Cmd_Help.java
=> fix: #853 helpコマンドが正常に動作しない不具合を修正

src/main/java/com/jaoafa/mymaid4/event/Event_CustomJoinLeftMessage.java
=> feat: #775 ログイン・ログアウトメッセージを英語化

src/main/java/com/jaoafa/mymaid4/Main.java, src/main/java/com/jaoafa/mymaid4/tasks/Task_OldWorldAutoRemove.java
=> feat: #738 ワールド自動アンロード実装

src/main/java/com/jaoafa/mymaid4/event/Event_jaoBox.java
=> fix(jaoBox): 旧サイズが0の場合にエラーが出る不具合を修正

.github/workflows/qodana-quality.yml, pom.xml
- https://github.com/jaoafa/MyMaid4/pull/860
- https://github.com/jaoafa/MyMaid4/pull/859
- https://github.com/jaoafa/MyMaid4/pull/829
- https://github.com/jaoafa/MyMaid4/pull/828
=> Update dependencies packages by renovate (2022-06-16)

src/main/java/com/jaoafa/mymaid4/event/Event_Looking.java
=> fix(looking): #884 pitch/yawがfiniteになる不具合修正

src/main/java/com/jaoafa/mymaid4/event/Event_ChatBot.java
=> fix: #887 ChatBot設定が未定義の時にNullPointerExceptionが発生する不具合修正

src/main/java/com/jaoafa/mymaid4/event/Event_AntiProblemCommand.java
=> feat: Verified以下による他人を対象としたeffectコマンドを拒否するように

src/main/java/com/jaoafa/mymaid4/event/Event_AntiProblemCommand.java
=> feat: #906 opコマンドの制限追加

.github/workflows/add-reviewer.yml
=> feat: #900 自動でレビュアーを追加する

src/main/java/com/jaoafa/mymaid4/lib/MCBansCache.java
=> fix: MCBansCacheのパラメーターがidではなくplayerIdだった

src/main/java/com/jaoafa/mymaid4/lib/MCBansCache.java
=> fix: #917 lastCheckedAtはStringなのにgetLongでとってた不具合の修正

src/main/java/com/jaoafa/mymaid4/event/Event_DailyOnlineTime.java
=> fix(DailyOnlineTime): #916 Mapに対象のUUIDキーがない場合にエラーが出る不具合修正

src/main/java/com/jaoafa/mymaid4/command/Cmd_Chat.java
- close #113 
次のようなコマンドが実行可能になります: `/chat "h o g e" piyo`
=> feat(Chat): プレイヤー名部分をクォートして指定できるように

src/main/java/com/jaoafa/mymaid4/event/Event_CommandFeedback.java, src/main/java/com/jaoafa/mymaid4/event/Event_CommandSender.java
- close #188 
従来、Verified以上のみ実行コマンドが実行者に対して表示されていましたが今回から全権限において実行コマンドが表示されるようになります。
=> fix: 実行したコマンドを全権限で表示するように

src/main/java/com/jaoafa/mymaid4/event/Event_SurvivalSitLay.java
=> feat: サバイバルモード/アドベンチャーモードでsit/layを使えないように

.github/workflows/qodana-quality.yml, pom.xml
- https://github.com/jaoafa/MyMaid4/pull/935
- https://github.com/jaoafa/MyMaid4/pull/934
- https://github.com/jaoafa/MyMaid4/pull/933
- https://github.com/jaoafa/MyMaid4/pull/932
- https://github.com/jaoafa/MyMaid4/pull/931
- https://github.com/jaoafa/MyMaid4/pull/872
- https://github.com/jaoafa/MyMaid4/pull/869
- https://github.com/jaoafa/MyMaid4/pull/868
=> Update dependencies packages by renovate (2022-09-01)

.github/workflows/qodana-clone-finder.yml, pom.xml
- https://github.com/jaoafa/MyMaid4/pull/945
- https://github.com/jaoafa/MyMaid4/pull/944
- https://github.com/jaoafa/MyMaid4/pull/943
- https://github.com/jaoafa/MyMaid4/pull/934
- https://github.com/jaoafa/MyMaid4/pull/869
- https://github.com/jaoafa/MyMaid4/pull/868
=> Update dependencies packages by renovate (2022-09-17)

src/main/java/com/jaoafa/mymaid4/command/Cmd_Bug.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_Feedback.java, src/main/java/com/jaoafa/mymaid4/event/Event_ClosedIssueNotifier.java, src/main/java/com/jaoafa/mymaid4/lib/IssueManager.java
=> feat: ログイン時、不具合報告・フィードバックがクローズされていたら通知する

src/main/java/com/jaoafa/mymaid4/lib/MyMaidConfig.java
- close https://github.com/jaoafa/MyMaid4/issues/958
=> fix: DiscordへGatewayIntent.MESSAGE_CONTENTをリクエストするように修正

pom.xml, src/main/java/com/jaoafa/mymaid4/Main.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_Bug.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_Feedback.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_Player.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_TpAlias.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_jaoBox.java, src/main/java/com/jaoafa/mymaid4/event/Event_SurvivalSitLay.java, src/main/java/com/jaoafa/mymaid4/lib/ConvLoc.java, src/main/java/com/jaoafa/mymaid4/lib/Historyjao.java, src/main/java/com/jaoafa/mymaid4/lib/Jail.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidCommand.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java, src/main/java/com/jaoafa/mymaid4/lib/TeleportAlias.java, src/main/java/com/jaoafa/mymaid4/tasks/Task_OldWorldAutoRemove.java
- close https://github.com/jaoafa/MyMaid4/pull/869
- close https://github.com/jaoafa/MyMaid4/pull/868
=> feat: cloud-paperとcloud-minecraft-extrasをv1.7.1に

pom.xml, src/main/java/com/jaoafa/mymaid4/discordEvent/DiscordEvent_Ready.java
=> chore: JDA v5.0.0-alpha.22

.github/workflows/qodana-quality.yml, .github/workflows/release.yml, pom.xml, src/main/java/com/jaoafa/mymaid4/discordEvent/DiscordEvent_Ready.java
- https://github.com/jaoafa/MyMaid4/pull/977
- https://github.com/jaoafa/MyMaid4/pull/975
- https://github.com/jaoafa/MyMaid4/pull/971
- https://github.com/jaoafa/MyMaid4/pull/970
- https://github.com/jaoafa/MyMaid4/pull/968
- https://github.com/jaoafa/MyMaid4/pull/967
- https://github.com/jaoafa/MyMaid4/pull/966
=> Update dependencies packages by renovate (2022-10-31)

.github/workflows/qodana-quality.yml, pom.xml
=> Update dependencies packages by renovate (2023-03-01)

.github/workflows/qodana-quality.yml, .github/workflows/release.yml, pom.xml
=> Update dependencies packages by renovate (2023-04-01)

.github/workflows/qodana-quality.yml, .github/workflows/release.yml, pom.xml
=> Update dependencies packages by renovate (2023-05-01)

pom.xml
=> Update dependencies packages by renovate (2023-07-01)
