jaoafa/MyMaid4

.mvn/maven.config, pom.xml, settings.xml
GitHub Packages で jSA2 のMavenリポジトリをホストするようになったことに伴い、jaotan で生成した Personal access token を使うはずだったのですが素のまま書いてしまったので GitHub 側でトークンを無効化されてしまい動かなくなっていました。それの修正です（エンコードしました）
https://github.community/t/how-to-allow-unauthorised-read-access-to-github-packages-maven-repository/115517/4
=> fix: jSA2のソース取得に失敗する問題

src/main/java/com/jaoafa/mymaid4/Main.java
dtコマンドなどのサジェストにおいて大文字小文字を区別しないように！
=> fix: 引数の大文字小文字区別を削除

src/main/java/com/jaoafa/mymaid4/event/Event_BlackList.java
エリトラなどの着けるものを手動でつけられない・外せない不具合の修正
- close #315 
- 【必須】[x] [CONTRIBUTING](https://github.com/jaoafa/MyMaid4/blob/master/CONTRIBUTING.md) を読みました
- 【必須】[x] テストサーバで動作確認をしました
- 【必須】[x] プロジェクトのコードスタイルに適合しています（IDEAのコミット前処理でフォーマットして下さい）
- 【必須】[x] `NULL` が返却されるかもしれない(`@Nullable`)メソッドや変数は NULL チェックを実装しました
=> fix: エリトラなどの着けるものを手動でつけられない・外せない不具合の修正

src/main/java/com/jaoafa/mymaid4/event/Event_AntiProblemCommand.java
bug, kickコマンドを引数無しで実行した際にエラーが発生する不具合の修正
- close #318 
=> fix: bug, kickコマンドを引数無しで実行した際にエラーが発生する不具合の修正

src/main/java/com/jaoafa/mymaid4/event/Event_Antijaoium.java
=> fix: #328 jaoium判定条件の修正

pom.xml
bintrayがForbiddenするようになったので、`repo.tomacheese.com` でホストするように変更
=> fix: bintrayのリポジトリ削除

src/main/java/com/jaoafa/mymaid4/event/Event_DedMessage.java, src/main/java/com/jaoafa/mymaid4/lib/DedMessage.java
一部ブロックがdedmessageの対象にならない不具合の修正
- close #334
=> fix: #334 一部ブロックがdedmessageの対象にならない不具合の修正

src/main/java/com/jaoafa/mymaid4/command/Cmd_Calctree.java
`/calctree true/false(両端に木を置くかどうか/Default:true)`
植木算機能を実装しました。
WEで選択した範囲を取得し、長いほう(x or z)を取得して植木算を実行します。
(選択範囲がどちらも3m以下の場合は弾かれます。)
結果が50以上ある場合は、余りが発生しない結果のみ表示します。
#326 
=> feat: calctree3

src/main/java/com/jaoafa/mymaid4/event/Event_LookingBlock.java
"LookingBlock"を、プレイヤーが現在見ているブロックに置き換えて実行します
(//set LookingBlock など)
=> feat: LookingBlock

src/main/java/com/jaoafa/mymaid4/command/Cmd_Weather.java
自分だけに反映されるWeatherコマンド
close #280
=> feat: weather コマンドの実装

src/main/java/com/jaoafa/mymaid4/event/Event_DisableConcreteTransition.java
コンクリ変化制限時パーティクルにblock_dustが選ばれた際にエラーになる不具合を修正
Fixes #265
Java なんもわからん
=> fix: コンクリ変化制限時パーティクルにblock_dustが選ばれた際にエラーになる不具合を修正

src/main/java/com/jaoafa/mymaid4/command/Cmd_Lead.java
①対象のエンティティを見てlead leaveで外せるように
②lead leaveをリードを付けられている側だけでなくリードを持っている側からも外せるように
③どのエンティティも見ていない状態で lead leaveしたら自分が持っているリードを外せるように
④上記の追加により他プレイヤーをlead leaveできてしまう問題について、他プレイヤーを実行対象外にするように
=> Kohonayoshi lead

src/main/java/com/jaoafa/mymaid4/event/Event_ManageCPPerms.java
=> fix: #263 coコマンドなどにおいて、引数なしだとエラーになる不具合

src/main/java/com/jaoafa/mymaid4/command/Cmd_History.java, src/main/java/com/jaoafa/mymaid4/lib/Historyjao.java
`/history add` を実行した際、公式Discord鯖 LOGGERカテゴリの `#jaohistory` チャンネルに通知する
close #518 
レビューよろ
=> feat: history addしたときにDiscord#jaohistoryに通知するように

src/main/java/com/jaoafa/mymaid4/event/Event_AntiProblemCommand.java
=> fix: #509 #526 kick, banを引数なしで実行時、エラーが出る問題の修正

src/main/java/com/jaoafa/mymaid4/command/Cmd_SecretTP.java, src/main/java/com/jaoafa/mymaid4/event/Event_CommandSendAM.java, src/main/java/com/jaoafa/mymaid4/event/Event_CommandSendR.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
- VDが実行したコマンドをRに送信
- クリックするとスぺテクターでテレポートできるように
- ↑で使うため`/secrettp`を実装
close #542
=> feat: Verifed以下が実行したコマンドをRegularに表示するように & AMに表示されるコマンドログの形式を変更 & secrettpコマンドの追加

src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java
=> fix: #533 埋めてあるマップは除外

src/main/java/com/jaoafa/mymaid4/command/Cmd_DedMessage.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_Home.java, src/main/java/com/jaoafa/mymaid4/event/Event_AntiDuplicateEntity.java, src/main/java/com/jaoafa/mymaid4/lib/Jail.java
#382 を実装 & ちょっと表示を変更(他機能)
close #382
=> feat: AntiDuplicateEntity

src/main/java/com/jaoafa/mymaid4/event/Event_Jail.java
- Jailの移動制限緩和（40ブロック→50ブロック）
- JailされているときはY55未満へは移動できないように
- close #568 
=> fix: #568 jailの移動制限緩和 + Y55未満へは行けないように

src/main/java/com/jaoafa/mymaid4/event/Event_DisableKicks.java, src/main/java/com/jaoafa/mymaid4/event/Event_NotifyKick.java
- #571 短時間のスパム行為によるkickの無効化修正 (`disconnect.spam`へ)
- キック時の通知メッセージを一部変更
- close #571 
なし
=> fix: #571 連投によるスパム判定を変更 (disconnect.spamへ)

src/main/java/com/jaoafa/mymaid4/lib/Jail.java
```
[Jail] プレイヤー「xxxxx」が遺言を残しました。
遺言: xxxxxxxxxxxxxxxx
```
-> 
```
[Jail] プレイヤー「xxxxx」が遺言を残しました。
[Jail] 遺言: xxxxxxxxxxxxxxxx
```
=> fix: testment時の全体通知メッセージが改行されているのを修正

src/main/java/com/jaoafa/mymaid4/command/Cmd_Weather.java
間違った天気を指定した際に警告するように
close #494 
close #383 
=> Fix: check is valid weather name

src/main/java/com/jaoafa/mymaid4/event/Event_AntiProblemCommand.java
- close #561
既に `/kill @p` 及び本人が自分をkillする場合はhistory追加等なかったので、`@s`だけ除外しました
=> fix: #561 kill @sを除外

.github/workflows/PaperServerTest.yml, .github/workflows/build.yml, .github/workflows/check-system-print.yml, .github/workflows/codeql-analysis.yml, .github/workflows/dependencies-update.yml, .github/workflows/release.yml, pom.xml
close #718 
This pull-request included the following updates:
- cloud-minecraft-extras v1.6.2 (fe6e84e)
- cloud-paper v1.6.2 (b53111c)
- jaosuperahievement2 v2.5.10 (5c7efe1)
- worldguard-bukkit v7.0.7 (e07696e)
- item-nbt-api v2.9.2 (19212c0)
- nbt-injector v2.9.2 (19212c0) <- いらなくね？
- actions/checkout v3 (e6b956e)
- actions/setup-java v3 (82077a5)
=> 依存パッケージアップデート 2022/03/08

pom.xml, src/main/java/com/jaoafa/mymaid4/event/Event_EBan.java, src/main/java/com/jaoafa/mymaid4/event/Event_Jail.java, src/main/java/com/jaoafa/mymaid4/lib/EBan.java, src/main/java/com/jaoafa/mymaid4/lib/Jail.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidData.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java
南の楽園の場所を修正しました。
> close #726 
DBがなくてjailできないので、✞本番環境でテスト✞になってしまうかも...
=> fix: 南の楽園の場所を変更

src/main/java/com/jaoafa/mymaid4/event/Event_Jail.java
hasWarned の null チェックを追加しました。
close #745
=> fix: jail時の警告処理でnullpointerが発生する不具合の修正

src/main/java/com/jaoafa/mymaid4/command/Cmd_Tips.java, src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java, src/main/java/com/jaoafa/mymaid4/lib/Tips.java
close #842
定型文送信・管理コマンド `tips` を実装します。
「どこにいるの？」に対する「DynmapURLの送信」、「.って何？」に対する文化に関するページへのリンクなど、よくある質問や応対のために利用できると思います。
- `/tips add <TipName> <Text>`: TipNameでTextを登録します。
- `/tips remove <TipName>`: TipNameのTipを削除します。
- `/tips broadcast <TipName>`: TipNameに紐づいたTip (Text)を送信します。メッセージはフェイクチャットとして投稿されます。
- `/tips list`: Tipsの一覧を表示します。
=> feat: tipsコマンドの実装

src/main/java/com/jaoafa/mymaid4/command/Cmd_G.java
- タイトル通りの修正をしました。
- ユーザーへメッセージを送るコードの一部が重複していたので、まとめました。
- `Adventure` が `Advanture` となっていたので、これも修正しました。
close #890 
=> /g で引数に大文字を指定できない問題を修正

src/main/java/com/jaoafa/mymaid4/command/Cmd_FlySpeed.java, src/main/java/com/jaoafa/mymaid4/command/Cmd_WalkSpeed.java
- `/walkspeed reset` `/flyspeed reset` を実装しました。
- walkspeed のデフォルト値を修正しました。(`0.1f` -> `0.2f`)
- close #897
- close #898 
=> /walkspeed,flyspeed reset を実装 & デフォルト値を修正

src/main/java/com/jaoafa/mymaid4/event/Event_AntiToolbar.java
- close #896 
ツールバー関連は仕組みがごちゃごちゃしているので、結構ツラいです。
このプルリクエストに紐付くIssueは #896 だけですが、多分 #429 とかも関係してくるんだろうと思います。
とりあえず今回で対応したものは次の2つです。
- 持ち上げたアイテムとして除外された時に入れ替わりで持ち上げたアイテム（頭スロットに既にあるアイテムをアイテムを持った状態で置き換えるなど）を他のスロットに置くとツールバーアイテム判定される問題
- 特殊な条件で起こるプレイヤーの頭のNBTデータ不一致問題
- `head` や `give` コマンドで入手したプレイヤーの頭には、頭として指定したプレイヤーのプレイヤー名やUUIDしか含まれていません。
- そのアイテムを持ち上げるなどすることで、そのプレイヤー情報に紐付くスキン情報（プロファイルデータ）が追記されます。
- これによって元々インベントリにあったアイテム情報と持ち上げた後移動したアイテム情報が不一致と判断され、ユーザからすると同一アイテムに見えるものがシステム的に同一ではなくなる…という面倒なことになっていました
- `isAllowPlayerHead` メソッドを作成し、プレイヤー名やUUIDが合致する場合は同一アイテムとして判定することで回避します。（逆に、この回避策はツールバーに細工されたプレイヤーの頭を入れておくことでツールバー判定を回避できるので難しいところです）
今後のためにクラスコメントをつけておきました。
=> fix: プレイヤーの頭がツールバー判定される問題の修正

.github/workflows/only-change-base.yml, .github/workflows/release.yml, .github/workflows/renovate-pr-dev.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> ci: changed to $GITHUB_OUTPUT from set-output

src/main/java/com/jaoafa/mymaid4/command/Cmd_G.java, src/main/java/com/jaoafa/mymaid4/event/Event_GameModeCmd.java
- close #1004 
g コマンドに gamemode エイリアスを追加します。これにより、数字でゲームモードを変更しようとするユーザーもカバーできるようになるかと思います。
なお、この変更によって「gamemodeコマンドを実行したときにgコマンドを勧める機能」は「`minecraft:gamemode`を実行したときのみ」になりました。
=> feat: gコマンドにgamemodeエイリアスを追加
